import React, { useState, useEffect, createContext, useContext } from "react";
import { useToast } from "@/hooks/use-toast";

// Language options
export const languages = [
  { code: "en", name: "English" },
  { code: "de", name: "German" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
];

// Translations for all components and pages
export const translations: {[key: string]: {[key: string]: string}} = {
  "en": {
    // Navbar translations
    "Home": "Home",
    "Properties": "Properties",
    "About Us": "About Us",
    "UAE Know How": "UAE Know How",
    "ROI & Investment": "ROI & Investment",
    "Company Setup": "Company Setup",
    "Financing": "Financing",
    "Crypto Buying": "Crypto Buying",
    "Blog": "Blog",
    "Contact": "Contact",
    "Book Consultation": "Book Consultation",
    "Language Detected": "Language Detected",
    "Language Changed": "Language Changed",
    "browserLangMessage": "Your browser language has been automatically selected.",
    "langChangeMessage": "The website language has been changed to",
    
    // Footer translations
    "Quick Links": "Quick Links",
    "Property Types": "Property Types",
    "Contact Us": "Contact Us",
    "Your premier partner": "Your premier partner for luxury property investments and company setup in Dubai and Ras Al Khaimah.",
    "Luxury Apartments": "Luxury Apartments",
    "Premium Villas": "Premium Villas",
    "Exclusive Penthouses": "Exclusive Penthouses",
    "Off-Plan Projects": "Off-Plan Projects",
    "All rights reserved": "All rights reserved",
    "Privacy Policy": "Privacy Policy",
    "Terms of Service": "Terms of Service",
    "Cookie Policy": "Cookie Policy",
    
    // Property page translations
    "Explore Our Properties": "Explore Our Properties",
    "Find your perfect investment": "Find your perfect investment opportunity in Dubai & Ras Al Khaimah",
    "Properties Found": "Properties Found",
    "No properties found": "No properties found",
    "Try adjusting your filters": "Try adjusting your filters to see more results",
    
    // Financing page translations
    "Property Financing Options": "Property Financing Options",
    "Explore mortgage and financing": "Explore mortgage and financing solutions for international investors",
    "Financing Your Dubai Property": "Financing Your Dubai Property",
    "Navigating the financing options": "Navigating the financing options for international property investments can be complex. We're here to simplify the process and help you find the best solutions.",
    "Mortgage Options": "Mortgage Options",
    "Explore a range of mortgage": "Explore a range of mortgage products from local and international banks, tailored to non-resident investors.",
    "Eligibility Criteria": "Eligibility Criteria",
    "Understand the key criteria": "Understand the key criteria for mortgage approval, including credit history, income verification, and property valuation.",
    "Loan-to-Value (LTV)": "Loan-to-Value (LTV)",
    "Learn about typical LTV": "Learn about typical LTV ratios for non-resident mortgages in Dubai and how they impact your down payment requirements.",
    "Our Financing Partners": "Our Financing Partners",
    "We work with leading banks": "We work with leading banks and financial institutions to offer you competitive rates and flexible financing solutions.",
    "Get Personalized Financing Advice": "Get Personalized Financing Advice",
    "Mortgage Calculator": "Mortgage Calculator",
    "Down Payment (%)": "Down Payment (%)",
    "Interest Rate (%)": "Interest Rate (%)",
    "Loan Term (Years)": "Loan Term (Years)",
    "Calculate Monthly Payment": "Calculate Monthly Payment",
    "Estimated Monthly Payment": "Estimated Monthly Payment",
    "Total Loan Amount": "Total Loan Amount",
    "Total Interest": "Total Interest",
    "Total Payment": "Total Payment",
    "Mortgage Calculation Complete": "Mortgage Calculation Complete",
    "Your estimated monthly payment is AED": "Your estimated monthly payment is AED",
    
    // ROI Calculator translations
    "ROI Calculator": "ROI Calculator",
    "Property Price (AED)": "Property Price (AED)",
    "Annual Rental Income (AED)": "Annual Rental Income (AED)",
    "Annual Expenses": "Annual Expenses",
    "Service Charge (AED)": "Service Charge (AED)",
    "Yearly Service Charge (AED)": "Yearly Service Charge (AED)",
    "Annual maintenance fee charged by the building management": "Annual maintenance fee charged by the building management",
    "Property Insurance (AED)": "Property Insurance (AED)",
    "Other Expenses (AED)": "Other Expenses (AED)",
    "Include management fees, maintenance costs, etc.": "Include management fees, maintenance costs, etc.",
    "Investment Returns": "Investment Returns",
    "Annual Return": "Annual Return",
    "Monthly Return": "Monthly Return",
    "Total ROI": "Total ROI",
    "Recalculate ROI": "Recalculate ROI",
    
    // Property Yearly Costs translations
    "Property Yearly Costs": "Property Yearly Costs",
    "Understanding the annual costs of property ownership in the UAE is essential for making informed investment decisions.": "Understanding the annual costs of property ownership in the UAE is essential for making informed investment decisions.",
    "Service Charges": "Service Charges",
    "Annual fees charged by building management for maintenance of common areas": "Annual fees charged by building management for maintenance of common areas",
    "Property Insurance": "Property Insurance",
    "Annual building insurance premium": "Annual building insurance premium",
    "DEWA Fees": "DEWA Fees",
    "Dubai Electricity and Water Authority charges": "Dubai Electricity and Water Authority charges",
    "Chiller Fees": "Chiller Fees",
    "District cooling charges for air conditioning": "District cooling charges for air conditioning",
    "Rate": "Rate",
    "Example Annual Cost": "Example Annual Cost",
    "Notes": "Notes",
    "Varies by building quality and amenities": "Varies by building quality and amenities",
    "Required for all properties": "Required for all properties",
    "Housing fee (5% of annual rent)": "Housing fee (5% of annual rent)",
    "Charged monthly through utility bills": "Charged monthly through utility bills",
    "Variable costs based on consumption": "Variable costs based on consumption",
    "Applies to properties with central cooling systems": "Applies to properties with central cooling systems",
    "Additional Considerations": "Additional Considerations",
    "Property taxes in Dubai are among the lowest globally": "Property taxes in Dubai are among the lowest globally",
    "No annual property tax as commonly found in other countries": "No annual property tax as commonly found in other countries",
    "One-time 4% property registration fee paid at purchase": "One-time 4% property registration fee paid at purchase",
    "Rental income is currently tax-free in the UAE": "Rental income is currently tax-free in the UAE",
    "Budget 1-2% of property value for annual maintenance": "Budget 1-2% of property value for annual maintenance",
    
    // UAE Real Estate Investment Benefits translations
    "Real Estate Investment Calculator": "Real Estate Investment Calculator",
    "Use our calculator to analyze potential returns on your Dubai property investment": "Use our calculator to analyze potential returns on your Dubai property investment",
    "UAE Real Estate Investment Benefits": "UAE Real Estate Investment Benefits",
    "Average Rental Yield": "Average Rental Yield",
    "Significantly higher than global average of 3-4%": "Significantly higher than global average of 3-4%",
    "Income & Property Tax": "Income & Property Tax",
    "Tax-free rental income and no annual property taxes": "Tax-free rental income and no annual property taxes",
    "Price Appreciation (2023)": "Price Appreciation (2023)",
    "Strong market growth continues post-pandemic": "Strong market growth continues post-pandemic",
    
    // Ready vs Off-Plan Comparison translations
    "Ready vs. Off-Plan: Investment Comparison": "Ready vs. Off-Plan: Investment Comparison",
    "Compare the benefits and considerations of investing in ready properties versus off-plan developments": "Compare the benefits and considerations of investing in ready properties versus off-plan developments",
    "Investment Strategy Comparison": "Investment Strategy Comparison",
    "Category": "Category",
    "Ready Property": "Ready Property",
    "Off-Plan Property": "Off-Plan Property",
    "Initial Investment": "Initial Investment",
    "Full payment or mortgage required upfront": "Full payment or mortgage required upfront",
    "Lower initial deposit (20-30%)": "Lower initial deposit (20-30%)",
    "Payment Plan": "Payment Plan",
    "Single payment or mortgage-based": "Single payment or mortgage-based",
    "Payment spread over construction period (2-5 years)": "Payment spread over construction period (2-5 years)",
    "Immediate Income": "Immediate Income",
    "Immediate rental income possible": "Immediate rental income possible",
    "No income until project completion": "No income until project completion",
    "Property Appreciation": "Property Appreciation",
    "Market value growth at standard rates": "Market value growth at standard rates",
    "Potential for higher appreciation upon completion": "Potential for higher appreciation upon completion",
    "Risk Level": "Risk Level",
    "Lower risk - property already exists": "Lower risk - property already exists",
    "Higher risk - potential construction delays": "Higher risk - potential construction delays",
    "Customization": "Customization",
    "Limited modification options": "Limited modification options",
    "More options for layouts and finishes": "More options for layouts and finishes",
    "Ready Property Example": "Ready Property Example",
    "Off-Plan Property Example": "Off-Plan Property Example",
    "Purchase Price": "Purchase Price",
    "7% yield": "7% yield",
    "Income Start": "Income Start",
    "Immediate": "Immediate",
    "5-Year Total Return": "5-Year Total Return",
    "Rental Income": "Rental Income",
    "Estimated Capital Appreciation": "Estimated Capital Appreciation",
    "Total Return": "Total Return",
    "Payment Structure": "Payment Structure",
    "20% Down Payment": "20% Down Payment",
    "80% Over 3 Years": "80% Over 3 Years",
    "After 3 years (completion)": "After 3 years (completion)",
    "Ready": "Ready",
    "Off-Plan": "Off-Plan",
    "View Details": "View Details",
    "Dubai": "Dubai",
    "Ras Al Khaimah": "Ras Al Khaimah",
    
    // Property Filter translations
    "Find Your Ideal Investment": "Find Your Ideal Investment",
    "Search Properties": "Search Properties",
    "Property Search": "Property Search",
    "Adjust filters to find your perfect property": "Adjust filters to find your perfect property",
    "Price Range": "Price Range",
    "Location": "Location",
    "All Locations": "All Locations",
    "Dubai Marina": "Dubai Marina",
    "Downtown Dubai": "Downtown Dubai",
    "Palm Jumeirah": "Palm Jumeirah",
    "Dubai Hills": "Dubai Hills",
    "Ras Al Khaimah": "Ras Al Khaimah",
    "Property Type": "Property Type",
    "All Types": "All Types",
    "Apartment": "Apartment",
    "Villa": "Villa",
    "Penthouse": "Penthouse",
    "Townhouse": "Townhouse",
    "Bedrooms": "Bedrooms",
    "Any": "Any",
    "Status": "Status",
    "All Properties": "All Properties",
    "Ready": "Ready",
    "Off-Plan": "Off-Plan",
    "Minimum ROI": "Minimum ROI",
    "Apply Filters": "Apply Filters",
  },
  "de": {
    // Navbar translations
    "Home": "Startseite",
    "Properties": "Immobilien",
    "About Us": "Über uns",
    "UAE Know How": "VAE Know-how",
    "ROI & Investment": "ROI & Investition",
    "Company Setup": "Firmengründung",
    "Financing": "Finanzierung",
    "Crypto Buying": "Krypto-Kauf",
    "Blog": "Blog",
    "Contact": "Kontakt",
    "Book Consultation": "Beratung buchen",
    "Language Detected": "Sprache erkannt",
    "Language Changed": "Sprache geändert",
    "browserLangMessage": "Ihre Browsersprache wurde automatisch ausgewählt.",
    "langChangeMessage": "Die Website-Sprache wurde geändert zu",
    
    // Footer translations
    "Quick Links": "Schnelllinks",
    "Property Types": "Immobilientypen",
    "Contact Us": "Kontaktieren Sie uns",
    "Your premier partner": "Ihr erstklassiger Partner für Luxusimmobilieninvestitionen und Firmengründung in Dubai und Ras Al Khaimah.",
    "Luxury Apartments": "Luxuswohnungen",
    "Premium Villas": "Premium-Villen",
    "Exclusive Penthouses": "Exklusive Penthäuser",
    "Off-Plan Projects": "Bauprojekte",
    "All rights reserved": "Alle Rechte vorbehalten",
    "Privacy Policy": "Datenschutzrichtlinie",
    "Terms of Service": "Nutzungsbedingungen",
    "Cookie Policy": "Cookie-Richtlinie",
    
    // Property page translations
    "Explore Our Properties": "Entdecken Sie unsere Immobilien",
    "Find your perfect investment": "Finden Sie Ihre perfekte Investitionsmöglichkeit in Dubai und Ras Al Khaimah",
    "Properties Found": "Immobilien gefunden",
    "No properties found": "Keine Immobilien gefunden",
    "Try adjusting your filters": "Versuchen Sie, Ihre Filter anzupassen, um mehr Ergebnisse zu sehen",
    
    // Financing page translations
    "Property Financing Options": "Immobilienfinanzierungsoptionen",
    "Explore mortgage and financing": "Entdecken Sie Hypotheken- und Finanzierungslösungen für internationale Investoren",
    "Financing Your Dubai Property": "Finanzierung Ihrer Dubai-Immobilie",
    "Navigating the financing options": "Die Navigation durch die Finanzierungsoptionen für internationale Immobilieninvestitionen kann komplex sein. Wir sind hier, um den Prozess zu vereinfachen und Ihnen zu helfen, die besten Lösungen zu finden.",
    "Mortgage Options": "Hypothekenoptionen",
    "Explore a range of mortgage": "Entdecken Sie eine Reihe von Hypothekenprodukten von lokalen und internationalen Banken, die auf nicht-ansässige Investoren zugeschnitten sind.",
    "Eligibility Criteria": "Zulassungskriterien",
    "Understand the key criteria": "Verstehen Sie die wichtigsten Kriterien für die Hypothekengenehmigung, einschließlich Kredithistorie, Einkommensnachweis und Immobilienbewertung.",
    "Loan-to-Value (LTV)": "Beleihungsquote (LTV)",
    "Learn about typical LTV": "Erfahren Sie mehr über typische LTV-Quoten für Nicht-Resident-Hypotheken in Dubai und wie sie sich auf Ihre Anzahlungsanforderungen auswirken.",
    "Our Financing Partners": "Unsere Finanzierungspartner",
    "We work with leading banks": "Wir arbeiten mit führenden Banken und Finanzinstituten zusammen, um Ihnen wettbewerbsfähige Zinssätze und flexible Finanzierungslösungen anzubieten.",
    "Get Personalized Financing Advice": "Holen Sie sich persönliche Finanzierungsberatung",
    "Mortgage Calculator": "Hypothekenrechner",
    "Property Price (AED)": "Immobilienpreis (AED)",
    "Down Payment (%)": "Anzahlung (%)",
    "Interest Rate (%)": "Zinssatz (%)",
    "Loan Term (Years)": "Kreditlaufzeit (Jahre)",
    "Calculate Monthly Payment": "Monatliche Rate berechnen",
    "Estimated Monthly Payment": "Geschätzte monatliche Rate",
    "Total Loan Amount": "Gesamtkreditbetrag",
    "Total Interest": "Gesamtzinsen",
    "Total Payment": "Gesamtzahlung",
    "Mortgage Calculation Complete": "Hypothekenberechnung abgeschlossen",
    "Your estimated monthly payment is AED": "Ihre geschätzte monatliche Rate beträgt AED",
    
    // ROI Calculator translations
    "ROI Calculator": "ROI-Rechner",
    "Annual Rental Income (AED)": "Jährliches Mieteinnahmen (AED)",
    "Annual Expenses": "Jährliche Ausgaben",
    "Service Charge (AED)": "Servicegebühr (AED)",
    "Yearly Service Charge (AED)": "Jährliche Servicegebühr (AED)",
    "Annual maintenance fee charged by the building management": "Jährliche Wartungsgebühr, die von der Gebäudeverwaltung erhoben wird",
    "Property Insurance (AED)": "Gebäudeversicherung (AED)",
    "Other Expenses (AED)": "Sonstige Ausgaben (AED)",
    "Include management fees, maintenance costs, etc.": "Inklusive Verwaltungsgebühren, Wartungskosten, etc.",
    "Investment Returns": "Anlagerenditen",
    "Annual Return": "Jährliche Rendite",
    "Monthly Return": "Monatliche Rendite",
    "Total ROI": "Gesamtrendite",
    "Recalculate ROI": "ROI neu berechnen",
    
    // Property Yearly Costs translations
    "Property Yearly Costs": "Jährliche Immobilienkosten",
    "Understanding the annual costs of property ownership in the UAE is essential for making informed investment decisions.": "Das Verständnis der jährlichen Kosten für Immobilienbesitz in den VAE ist für fundierte Investitionsentscheidungen unerlässlich.",
    "Service Charges": "Servicegebühren",
    "Annual fees charged by building management for maintenance of common areas": "Jährliche Gebühren, die von der Gebäudeverwaltung für die Instandhaltung der Gemeinschaftsbereiche erhoben werden",
    "Property Insurance": "Gebäudeversicherung",
    "Annual building insurance premium": "Jährliche Gebäudeversicherungsprämie",
    "DEWA Fees": "DEWA-Gebühren",
    "Dubai Electricity and Water Authority charges": "Gebühren der Dubai Elektrizitäts- und Wasserbehörde",
    "Chiller Fees": "Kühlanlagengebühren",
    "District cooling charges for air conditioning": "Gebühren für Fernkühlung zur Klimatisierung",
    "Rate": "Satz",
    "Example Annual Cost": "Beispiel Jahreskosten",
    "Notes": "Hinweise",
    "Varies by building quality and amenities": "Variiert je nach Gebäudequalität und Ausstattung",
    "Required for all properties": "Erforderlich für alle Immobilien",
    "Housing fee (5% of annual rent)": "Wohngebühr (5% der Jahresmiete)",
    "Charged monthly through utility bills": "Monatlich über Nebenkosten abgerechnet",
    "Variable costs based on consumption": "Variable Kosten basierend auf dem Verbrauch",
    "Applies to properties with central cooling systems": "Gilt für Immobilien mit zentralen Kühlsystemen",
    "Additional Considerations": "Zusätzliche Überlegungen",
    "Property taxes in Dubai are among the lowest globally": "Die Grundsteuern in Dubai gehören zu den niedrigsten weltweit",
    "No annual property tax as commonly found in other Ländern üblich": "Keine jährliche Grundsteuer wie in anderen Ländern üblich",
    "One-time 4% property registration fee paid at purchase": "Einmalige 4% Immobilienregistrierungsgebühr beim Kauf",
    "Rental income is currently tax-free in the UAE": "Mieteinnahmen sind derzeit in den VAE steuerfrei",
    "Budget 1-2% of property value for annual maintenance": "Budgetieren Sie 1-2% des Immobilienwerts für die jährliche Wartung",
    
    // UAE Real Estate Investment Benefits translations
    "Real Estate Investment Calculator": "Immobilieninvestitionsrechner",
    "Use our calculator to analyze potential returns on your Dubai property investment": "Nutzen Sie unseren Rechner, um potenzielle Renditen Ihrer Dubai-Immobilieninvestition zu analysieren",
    "UAE Real Estate Investment Benefits": "Vorteile von Immobilieninvestitionen in den VAE",
    "Average Rental Yield": "Durchschnittliche Mietrendite",
    "Significantly higher than global average of 3-4%": "Deutlich höher als der globale Durchschnitt von 3-4%",
    "Income & Property Tax": "Einkommens- & Grundsteuer",
    "Tax-free rental income and no annual property taxes": "Steuerfreies Mieteinkommen und keine jährlichen Grundsteuern",
    "Price Appreciation (2023)": "Preissteigerung (2023)",
    "Strong market growth continues post-pandemic": "Starkes Marktwachstum setzt sich nach der Pandemie fort",
    
    // Ready vs Off-Plan Comparison translations
    "Ready vs. Off-Plan: Investment Comparison": "Fertig vs. Rohbau: Investitionsvergleich",
    "Compare the benefits and considerations of investing in ready properties versus off-plan developments": "Vergleichen Sie die Vorteile und Überlegungen bei der Investition in fertige Immobilien versus Immobilien im Rohbau",
    "Investment Strategy Comparison": "Vergleich der Anlagestrategien",
    "Category": "Kategorie",
    "Ready Property": "Fertige Immobilie",
    "Off-Plan Property": "Immobilie im Rohbau",
    "Initial Investment": "Anfangsinvestition",
    "Full payment or mortgage required upfront": "Vollständige Zahlung oder Hypothek im Voraus erforderlich",
    "Lower initial deposit (20-30%)": "Niedrigere Anfangseinzahlung (20-30%)",
    "Payment Plan": "Zahlungsplan",
    "Single payment or mortgage-based": "Einmalzahlung oder hypothekenbasiert",
    "Payment spread over construction period (2-5 years)": "Zahlung über die Bauzeit verteilt (2-5 Jahre)",
    "Immediate Income": "Sofortiges Einkommen",
    "Immediate rental income possible": "Sofortiges Mieteinkommen möglich",
    "No income until project completion": "Kein Einkommen bis zur Fertigstellung des Projekts",
    "Property Appreciation": "Immobilienwertsteigerung",
    "Market value growth at standard rates": "Marktwert wächst mit Standardraten",
    "Potential for higher appreciation upon completion": "Potenzial für höhere Wertsteigerung bei Fertigstellung",
    "Risk Level": "Risikoniveau",
    "Lower risk - property already exists": "Geringeres Risiko - Immobilie existiert bereits",
    "Higher risk - potential construction delays": "Höheres Risiko - mögliche Bauverzögerungen",
    "Customization": "Anpassungsmöglichkeiten",
    "Limited modification options": "Begrenzte Änderungsmöglichkeiten",
    "More options for layouts and finishes": "Mehr Optionen für Grundrisse und Ausstattung",
    "Ready Property Example": "Beispiel für fertige Immobilie",
    "Off-Plan Property Example": "Beispiel für Immobilie im Rohbau",
    "Purchase Price": "Kaufpreis",
    "Annual Rental Income": "Jährliches Mieteinkommen",
    "7% yield": "7% Rendite",
    "Income Start": "Einkommensbeginn",
    "Immediate": "Sofort",
    "5-Year Total Return": "5-Jahres-Gesamtrendite",
    "Rental Income": "Mieteinkommen",
    "Estimated Capital Appreciation": "Geschätzte Kapitalwertsteigerung",
    "Total Return": "Gesamtrendite",
    "Payment Structure": "Zahlungsstruktur",
    "20% Down Payment": "20% Anzahlung",
    "80% Over 3 Years": "80% über 3 Jahre",
    "After 3 years (completion)": "Nach 3 Jahren (Fertigstellung)",
    "Ready": "Fertig",
    "Off-Plan": "Rohbau",
    "View Details": "Details anzeigen",
    "Dubai": "Dubai",
    "Ras Al Khaimah": "Ras Al Khaimah",
    
    // Property Filter translations
    "Find Your Ideal Investment": "Finden Sie Ihre ideale Investition",
    "Search Properties": "Immobilien suchen",
    "Property Search": "Immobiliensuche",
    "Adjust filters to find your perfect property": "Passen Sie die Filter an, um Ihre perfekte Immobilie zu finden",
    "Price Range": "Preisklasse",
    "Location": "Standort",
    "All Locations": "Alle Standorte",
    "Dubai Marina": "Dubai Marina",
    "Downtown Dubai": "Downtown Dubai",
    "Palm Jumeirah": "Palm Jumeirah",
    "Dubai Hills": "Dubai Hills",
    "Ras Al Khaimah": "Ras Al Khaimah",
    "Property Type": "Immobilientyp",
    "All Types": "Alle Typen",
    "Apartment": "Wohnung",
    "Villa": "Villa",
    "Penthouse": "Penthouse",
    "Townhouse": "Reihenhaus",
    "Bedrooms": "Schlafzimmer",
    "Any": "Beliebig",
    "Status": "Status",
    "All Properties": "Alle Immobilien",
    "Ready": "Bezugsfertig",
    "Off-Plan": "Im Bau",
    "Minimum ROI": "Mindestrendite",
    "Apply Filters": "Filter anwenden",
  },
  "ru": {
    // Navbar translations
    "Home": "Главная",
    "Properties": "Недвижимость",
    "About Us": "О нас",
    "UAE Know How": "Все об ОАЭ",
    "ROI & Investment": "ROI и Инвестиции",
    "Company Setup": "Регистрация компании",
    "Financing": "Финансирование",
    "Crypto Buying": "Покупка за криптовалюту",
    "Blog": "Блог",
    "Contact": "Контакты",
    "Book Consultation": "Записаться на консультацию",
    "Language Detected": "Язык определен",
    "Language Changed": "Язык изменен",
    "browserLangMessage": "Язык вашего браузера был выбран автоматически.",
    "langChangeMessage": "Язык сайта был изменен на",
    
    // Footer translations
    "Quick Links": "Быстрые ссылки",
    "Property Types": "Типы недвижимости",
    "Contact Us": "Свяжитесь с нами",
    "Your premier partner": "Ваш премиальный партнер для инвестиций в элитную недвижимость и создания компаний в Дубае и Рас-аль-Хайме.",
    "Luxury Apartments": "Элитные апартаменты",
    "Premium Villas": "Премиальные виллы",
    "Exclusive Penthouses": "Эксклюзивные пентхаусы",
    "Off-Plan Projects": "Проекты на стадии строительства",
    "All rights reserved": "Все права защищены",
    "Privacy Policy": "Политика конфиденциальности",
    "Terms of Service": "Условия использования",
    "Cookie Policy": "Политика использования файлов cookie",
    
    // Property page translations
    "Explore Our Properties": "Изучите нашу недвижимость",
    "Find your perfect investment": "Найдите идеальную инвестиционную возможность в Дубае и Рас-аль-Хайме",
    "Properties Found": "Найдено объектов",
    "No properties found": "Объекты не найдены",
    "Try adjusting your filters": "Попробуйте изменить параметры фильтра, чтобы увидеть больше результатов",
    
    // Financing page translations
    "Property Financing Options": "Варианты финансирования недвижимости",
    "Explore mortgage and financing": "Изучите ипотечные и финансовые решения для международных инвесторов",
    "Financing Your Dubai Property": "Финансирование вашей недвижимости в Дубае",
    "Navigating the financing options": "Навигация по вариантам финансирования для международных инвестиций в недвижимость может быть сложной. Мы здесь, чтобы упростить процесс и помочь вам найти лучшие решения.",
    "Mortgage Options": "Варианты ипотеки",
    "Explore a range of mortgage": "Изучите ряд ипотечных продуктов от местных и международных банков, специально для нерезидентов-инвесторов.",
    "Eligibility Criteria": "Критерии правомочности",
    "Understand the key criteria": "Понимание ключевых критериев для одобрения ипотеки, включая кредитную историю, подтверждение дохода и оценку недвижимости.",
    "Loan-to-Value (LTV)": "Отношение кредита к стоимости (LTV)",
    "Learn about typical LTV": "Узнайте о типичных соотношениях LTV для ипотеки нерезидентов в Дубае и как они влияют на требования к первоначальному взносу.",
    "Our Financing Partners": "Наши финансовые партнеры",
    "We work with leading banks": "Мы работаем с ведущими банками и финансовыми учреждениями, чтобы предложить вам конкурентоспособные ставки и гибкие решения по финансированию.",
    "Get Personalized Financing Advice": "Получите персонализированный финансовый совет",
    "Mortgage Calculator": "Ипотечный калькулятор",
    "Property Price (AED)": "Цена недвижимости (AED)",
    "Down Payment (%)": "Первоначальный взнос (%)",
    "Interest Rate (%)": "Процентная ставка (%)",
    "Loan Term (Years)": "Срок кредита (лет)",
    "Calculate Monthly Payment": "Рассчитать ежемесячный платеж",
    "Estimated Monthly Payment": "Ориентировочный ежемесячный платеж",
    "Total Loan Amount": "Общая сумма кредита",
    "Total Interest": "Общие проценты",
    "Total Payment": "Общий платеж",
    "Mortgage Calculation Complete": "Расчет ипотеки завершен",
    "Your estimated monthly payment is AED": "Ваш ориентировочный ежемесячный платеж составляет AED",
    
    // ROI Calculator translations
    "ROI Calculator": "Калькулятор рентабельности инвестиций",
    "Annual Rental Income (AED)": "Годовой доход от аренды (AED)",
    "Annual Expenses": "Годовые расходы",
    "Service Charge (AED)": "Сервисный сбор (AED)",
    "Yearly Service Charge (AED)": "Ежегодный сервисный сбор (AED)",
    "Annual maintenance fee charged by the building management": "Ежегодная плата за обслуживание, взимаемая управлением здания",
    "Property Insurance (AED)": "Страхование недвижимости (AED)",
    "Other Expenses (AED)": "Прочие расходы (AED)",
    "Include management fees, maintenance costs, etc.": "Включая плату за управление, расходы на обслуживание и т.д.",
    "Investment Returns": "Доходность инвестиций",
    "Annual Return": "Годовой доход",
    "Monthly Return": "Ежемесячный доход",
    "Total ROI": "Общая рентабельность",
    "Recalculate ROI": "Пересчитать ROI",
    
    // Property Yearly Costs translations
    "Property Yearly Costs": "Ежегодные расходы на недвижимость",
    "Understanding the annual costs of property ownership in the UAE is essential for making informed investment decisions.": "Понимание ежегодных расходов на владение недвижимостью в ОАЭ необходимо для принятия обоснованных инвестиционных решений.",
    "Service Charges": "Сервисные сборы",
    "Annual fees charged by building management for maintenance of common areas": "Ежегодные сборы, взимаемые управлением здания за обслуживание общих территорий",
    "Property Insurance": "Страхование недвижимости",
    "Annual building insurance premium": "Ежегодная страховая премия здания",
    "DEWA Fees": "Сборы DEWA",
    "Dubai Electricity and Water Authority charges": "Сборы Управления электричества и воды Дубая",
    "Chiller Fees": "Плата за охлаждение",
    "District cooling charges for air conditioning": "Плата за централизованное охлаждение для кондиционирования",
    "Rate": "Ставка",
    "Example Annual Cost": "Пример годовых расходов",
    "Notes": "Примечания",
    "Varies by building quality and amenities": "Варьируется в зависимости от качества здания и удобств",
    "Required for all properties": "Необходимо для всех объектов недвижимости",
    "Housing fee (5% of annual rent)": "Жилищный сбор (5% от годовой арендной платы)",
    "Charged monthly through utility bills": "Взимается ежемесячно через счета за коммунальные услуги",
    "Variable costs based on consumption": "Переменные затраты на основе потребления",
    "Applies to properties with central cooling systems": "Применяется к объектам с центральными системами охлаждения",
    "Additional Considerations": "Дополнительные соображения",
    "Property taxes in Dubai are among the lowest globally": "Налоги на недвижимость в Дубае одни из самых низких в мире",
    "No annual property tax as commonly found in other countries": "Отсутствие ежегодного налога на недвижимость, как в других странах",
    "One-time 4% property registration fee paid at purchase": "Единовременный 4% сбор за регистрацию недвижимости при покупке",
    "Rental income is currently tax-free in the UAE": "Доход от аренды в настоящее время не облагается налогом в ОАЭ",
    "Budget 1-2% of property value for annual maintenance": "Бюджет 1-2% от стоимости недвижимости на ежегодное обслуживание",
    
    // UAE Real Estate Investment Benefits translations
    "Real Estate Investment Calculator": "Калькулятор инвестиций в недвижимость",
    "Use our calculator to analyze potential returns on your Dubai property investment": "Используйте наш калькулятор для анализа потенциальной доходности ваших инвестиций в недвижимость Дубая",
    "UAE Real Estate Investment Benefits": "Преимущества инвестиций в недвижимость ОАЭ",
    "Average Rental Yield": "Средняя доходность от аренды",
    "Significantly higher than global average of 3-4%": "Значительно выше глобального среднего показателя в 3-4%",
    "Income & Property Tax": "Налог на доход и недвижимость",
    "Tax-free rental income and no annual property taxes": "Безналоговый доход от аренды и отсутствие ежегодных налогов на недвижимость",
    "Price Appreciation (2023)": "Рост цен (2023)",
    "Strong market growth continues post-pandemic": "Сильный рост рынка продолжается после пандемии",
    
    // Ready vs Off-Plan Comparison translations
    "Ready vs. Off-Plan: Investment Comparison": "Готовая vs. Строящаяся: Сравнение инвестиций",
    "Compare the benefits and considerations of investing in ready properties versus off-plan developments": "Сравните преимущества и особенности инвестирования в готовую недвижимость и в строящиеся объекты",
    "Investment Strategy Comparison": "Сравнение инвестиционных стратегий",
    "Category": "Категория",
    "Ready Property": "Готовая недвижимость",
    "Off-Plan Property": "Строящаяся недвижимость",
    "Initial Investment": "Начальные инвестиции",
    "Full payment or mortgage required upfront": "Требуется полная оплата или ипотека сразу",
    "Lower initial deposit
